### ISSUE TITLE
The "Bare minimum example:" code block is not rendered for exception 1476107941

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Exceptions#87]
* docs page: https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1476107941.html
* source: https://docs.typo3.org/typo3cms/exceptions/main/en-us/_sources/Exceptions/1476107941.rst.txt

source:
```

Bare minimum example:

.. code-block::yaml

   services:
     _defaults:
       # ...
       autoconfigure: true
       # ...

   # ...



[TYPO3 LTS 10] - [2021.05.05]
====================================
```

rendered:

![image](https://user-images.githubusercontent.com/13206455/198077965-f02ed20b-2760-4dc5-8b8b-dc8d746ca94c.png)
